// eslint-disable-next-line import/no-extraneous-dependencies
import 'tailwindcss/tailwind.css'
import type { AppProps } from 'next/app'
import { SessionProvider, signOut } from 'next-auth/react'
import Head from 'next/head'
import { AuthCheck, AuthProvider, Layout } from '../components'
import type { NextPage } from 'next'

export type NextApplicationPage<P = any, IP = P> = NextPage<P, IP> & {
  requireAuth?: boolean
}

function MyApp(props: AppProps) {
  const {
    Component,
    pageProps: { session, ...pageProps },
  }: { Component: NextApplicationPage; pageProps: any } = props

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Course Platform</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AuthProvider>
        {Component.requireAuth ? (
          <AuthCheck>
            <Component {...pageProps} />
          </AuthCheck>
        ) : (
          <Component {...pageProps} />
        )}
      </AuthProvider>
    </SessionProvider>
  )
}
export default MyApp
