// eslint-disable-next-line import/no-extraneous-dependencies
import 'tailwindcss/tailwind.css'
import type { AppProps } from 'next/app'
import { Layout } from '../components/layout'
import { SessionProvider } from 'next-auth/react'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  // const { data: session } = useSession()
  // console.log('session', session)
  return (
    <SessionProvider>
      <Head>
        <title>Course Platform</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </SessionProvider>
  )
}
export default MyApp
